### ISSUE TITLE
登录进去之后信息都查看不了

### ISSUE THREAD

**Issue by dafhf** [Soarkey/StudentManagement#22]
管理员身份登录进入之后点击查看学生信息等查看按钮，没任何反应，没报错，但查看不了，数据库已改为utf-8编码
能登陆也排除了连接不了数据库的问题，大佬求教

**Comment by dafhf** [comment]
问题补充：不只是信息查看不了，所有涉及数据库修改上传的操作都没有反应，网页也没有跳转

**Comment by dafhf** [comment]
再次补充问题，应该是前端js代码发送到java时出现了错误，怀疑是XMLHttpRequest()类的问题，是需要什么新的模块还是新的组件呢？

**Comment by dafhf** [comment]
发现在登录时候js代码中xmlhttp的xmlhttp.readyState和xmlhttp.status == 200不能实现
     if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {

            document.getElementById("result").innerHTML = xmlhttp.responseText;
        }
    }
这段代码就形同虚设了

**Comment by dafhf** [comment]
问题已解决，导出包时项目的(http://localhost:8080/之后的内容必须是StudentManagement,即项目运行时浏览器显示的地址必须是(http://localhost:8080/StudentManagement/]这样格式开头才正确，若错误重新配置tomcat，在idea上配置工件，修改名字即可实现

**Comment by ACGzhanshi** [comment]
![image](https://github.com/Soarkey/StudentManagement/assets/128225736/be0235d8-1cac-4472-b558-3c35a5c71fdc)
大佬问下这个模块原idea没有有影响吗
