### ISSUE TITLE
问题已解决，导出包时项目的(http://localhost:8080/之后的内容必须是StudentManagement,即项目运行时浏览器显示的地址必须是(http://localhost:8080/StudentManagement/]这样格式开头才正确，若错误重新配置tomcat，在idea上配置工件，修改名字即可实现

### ISSUE THREAD

**Issue by dafhf** [Soarkey/StudentManagement#23]
问题已解决，运行项目时候浏览器的地址中的(http://localhost:8080/之后的内容必须是StudentManagement,显示的地址必须是http://localhost:8080/StudentManagement/这样格式开头才正确，若错误重新配置tomcat，在idea上配置工件，修改名字即可实现

_Originally posted by @dafhf in https://github.com/Soarkey/StudentManagement/issues/22#issuecomment-1151104413_

**Comment by Real-77** [comment]
> 问题已解决，运行项目时候浏览器的地址中的([http://localhost:8080/之后的内容必须是StudentManagement,显示的地址必须是http://localhost:8080/StudentManagement/这样格式开头才正确，若错误重新配置tomcat，在idea上配置工件，修改名字即可实现](http://localhost:8080/%E4%B9%8B%E5%90%8E%E7%9A%84%E5%86%85%E5%AE%B9%E5%BF%85%E9%A1%BB%E6%98%AFStudentManagement,%E6%98%BE%E7%A4%BA%E7%9A%84%E5%9C%B0%E5%9D%80%E5%BF%85%E9%A1%BB%E6%98%AFhttp://localhost:8080/StudentManagement/%E8%BF%99%E6%A0%B7%E6%A0%BC%E5%BC%8F%E5%BC%80%E5%A4%B4%E6%89%8D%E6%AD%A3%E7%A1%AE%EF%BC%8C%E8%8B%A5%E9%94%99%E8%AF%AF%E9%87%8D%E6%96%B0%E9%85%8D%E7%BD%AEtomcat%EF%BC%8C%E5%9C%A8idea%E4%B8%8A%E9%85%8D%E7%BD%AE%E5%B7%A5%E4%BB%B6%EF%BC%8C%E4%BF%AE%E6%94%B9%E5%90%8D%E5%AD%97%E5%8D%B3%E5%8F%AF%E5%AE%9E%E7%8E%B0)
> 
> _Originally posted by @dafhf in [#22 (comment)](https://github.com/Soarkey/StudentManagement/issues/22#issuecomment-1151104413)_

请问改项目是如何运行的？小白一个，配置完成之后点击运行tomcat一直是404

**Comment by lemonsolid-2** [comment]
你的方法有误，名称不完整，和项目名对不上

**Comment by SamWang8888** [comment]
> 你的方法有误，名称不完整，和项目名对不上

哥 真心求教

**Comment by SamWang8888** [comment]
哥 真心求教 浏览器url都是一样的 但还是404

**Comment by dafhf** [comment]
#
